### PR TITLE
Ability to cache post, patch, put, delete methods

### PR DESCRIPTION
**Pull request by mohamedgomran**
Adding ability to cache post, patch, put, delete methods and making cache stale when request body changes.

### CODE REVIEW

**Comment by RasCarlito** [comment]
Nice technique to get it working! But coverage has massively dropped on `src/cache.js` file 😞

**Comment by mohamedgomran** [comment]
@RasCarlito I was proposing the PR and will write the required tests if it would be merged

**Comment by RasCarlito** [comment]
Ok! Well if you are up for it I'll merge it when it is done.
Also if you could rebase your branch on origin/master so that only the commits related to this modification show up it'd be awesome.
Cheers

**Comment by mohamedgomran** [comment]
@RasCarlito Tests done coverage is increased by 0.02% :"D

**Comment by mohamedgomran** [comment]
@RasCarlito Any updates?

**Comment by Epick362** [comment]
Any update on this @RasCarlito ? This would be a very handy feature.

**Comment by RasCarlito** [comment]
Sorry for not getting back to you.

Merging this and planning a release very soon 🚀 

Cheers

**Comment by soberams** [comment]
@RasCarlito could you please tell which version has this code change? Or has it not been released yet?

**Comment by OliverEvans96** [comment]
Looks like there hasn't been a new release since this was merged. Would be great to see it published!

**Pull request merged**
