### PR TITLE
Fix getTag function in utilities to make sure toString refers to Object.prototype.toString and not window.toString

### PR DESCRIPTION
**Pull request by erikagiroux**
The line `const toString = Object.prototype.toString` from getTag.js was missing when the lodash functions were copied to utilities.js because it was outside of the function.

The result is that toString was referring to window.toString instead of Object.prototype.toString. They are identical  in most modern browsers but not on older browsers like IE11 so it was causing errors.

See issue #142

### CODE REVIEW

**Comment by AndrewCraswell** [comment]
@RasCarlito Is it possible to get this hot fixed soon? It does fix an existing live site broken issue on IE 11 browsers.

@erikagiroux If you have a venmo, paypal, or cash app let me know :)

**Comment by erikagiroux** [comment]
@AndrewCraswell No need. It was literally just one line of code 😉 I hope it helps once it's merged.

**Comment by RasCarlito** [comment]
Hey! Thanks a lot for this fix.
I will just push the dist rebuilt onto your branch to get it merged 😃 

Cheers

**Comment by erikagiroux** [comment]
@RasCarlito I merged master into my branch but I was not able to commit because the linter found some errors after standard was updated in 22f6192c94e41accef17cc84f50e688c6a12a7f9 so I had to modify some other files to fix all errors.

The main error was about `assert.equal` being deprecated in the tests. I had to change every test to use only strict equality checks (`assert.strictEqual`). One of the Redis tests (removeItem(): Should remove an item) no longer passed. It was expecting `undefined` but the value was `null` (which appears to be the right result when an item does not exist in the Redis store). So I had to change that test too.

Can you check if everything is ok?

**Comment by mjoyce91** [comment]
Any update on getting this merged?

**Comment by Jimjam89** [comment]
Will this be merged and released soon? Just had to downgrade to 2.4.1 to work with IE11

**Comment by Brain2000** [comment]
Should we do a fresh pull request to fix this?

**Comment by erikagiroux** [comment]
@Brain2000 It might help. This branch is too far behind to be merged as is so a new commit with only the fix + a rebuild would probably be better at this point.

The original fix is just one line in utilities:
https://github.com/RasCarlito/axios-cache-adapter/pull/145/commits/b29b1690a8e32312404f601f0dfa24630b031bed#diff-b5c8f479fd199c465e4e5fce91bed60d

Just let me know if you open a new PR so I can close this one.

**Comment by Brain2000** [comment]
New PR created.

**Comment by Brain2000** [comment]
I see he also asked for the dist folder to get built, I may do that for him real fast as well.

**Comment by erikagiroux** [comment]
Closing this because #199 fixes the same issue

**Pull request closed without merging**
