### PR TITLE
feat: update axios to v0.20.x (#214)

### LINKED ISSUE #214: Axios is out of date
Axios is now at v0.20.0 and the issues with 0.19.0 seem to have been solved.

### PR DESCRIPTION
**Pull request by jahead**
All tests past locally
fixes #214

### CODE REVIEW

**Comment by AJHenry** [comment]
Anyway we can get this merged in? There was a fix with how axios interacts with [proxies release in 0.19](https://github.com/axios/axios/issues/1877) that would be really nice to have

**Comment by teklakct** [comment]
👍

**Comment by jahead** [comment]
@RasCarlito Everything okay mate? We haven't heard from you?

**Comment by joselcc** [comment]
any plan to this being merged?

**Comment by merobal** [comment]
The latest is now v0.21.1

**Comment by merobal** [comment]
@RasCarlito any plan to update this?

**Comment by teklakct** [comment]
In my project, a temporary fix is made by setting `axios` in a specific version in dependencies.

**Comment by merobal** [comment]
The previous versions contain vulnerabilities :( (only fixed in v0.21.1)

**Comment by jahead** [comment]
I'm not sure what we should do here, the maintainer hasn't responded to anything. And we need a new release. Can we temporarily fork the project, and publish an alternative until rascalito gets back on his feet? I hope he's okay!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by maxwellsmart84** [comment]
Wow this thread is active - i am ok with the forking - does anyone know the maintainer?

**Comment by maxwellsmart84** [comment]
@jahead can you bump axios to the latest and then fork this to another repo?

**Comment by teklakct** [comment]
Please put a link here to forked repository

**Comment by jahead** [comment]
https://github.com/jahead/axios-cache-adapter
Okay, 
I've bumped and run the tests, it all checks out.
I just quickly bumped the axios to "~0.21.1" for peer and dev deps.

I also rebuilt the dist folder. 

This is just a stop gap. We should probably put this fork under a organization, and  find out who wants to put time into reviewing the current PRs. and we need to publish to the npm store - I'm just praying @RasCarlito will poke his head in. 

we could do @axios-cache/adapter?

**Comment by maxwellsmart84** [comment]
I sent a LinkedIn message/request to @RasCarlito to ask him about maintaining this library.  Maybe we will get a response, all his contact information is on his GH profile though.

**Comment by jahead** [comment]
Yea I've sent him an email as well hopefully we can get through to him

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jahead** [comment]
@maxwellsmart84 we should wait for a response before making an issue about it, maybe Monday?
 
I've also parked the spaces. If we pull the trigger on this, I'll make a issue.

**Comment by genesiscz** [comment]
For now 
```
npm install https://github.com/jahead/axios-cache-adapter.git
```

worked

**Review by RasCarlito — APPROVED** [review]

**Comment by teklakct** [comment]
source

**Comment by jahead** [comment]
@RasCarlito Yea! if you need any help mate, please let us know. We use this project internally so I can put some work time to helping!

I'll close out the organizations that I parked

**Pull request merged**
