### PR TITLE
Add feature to read stale cache when a network error occurs

### LINKED ISSUE #20: Get stale cache on network error
Hi,

I would like to be able to return the cache when Axios returns a network error. From what I can see it is not possible as it is because the cache store throws an error when the cache is stale. And also because there is no wrapper try/catch around the call to the default adapter. Is that right?

Would you be interested in supporting such feature? If yes, how would you recommend it to be coded?

Thanks!
Fred

### PR DESCRIPTION
**Pull request by ghost**
Fixes #20

### CODE REVIEW

**Comment by FMCorz** [comment]
Hi @RasCarlito,

I'm new to your library, so I may not grasp it all just yet, but if I may express my opinion, here they are:

1. This is similar to my implementation, but I find the need to ask the store for the same data twice to be unnecessary. When I looked at the code, I thought that the error itself could include the data that was returned from the cache, so you could leave it to the dev (or the exception) to deal with it. 

2. Returning the stale cache on any type of error is tricy, and I would not recommend it. The use case I'm having is that I want my app to still be running when the network goes down, or appear to be running rather. It's meant to be an SPA displayed in "kiosk" mode on an ipad, in a public space. I cannot afford the network to go down for reasons I won't go into, and thus I want the cache to kick in when that's the case. However, I do not have any use case for handling server errors, those are separate. So, I think there is a need to differentiate between _readOnError_ and _readOnNetworkError_. Which leads me to 3.

3. Would it be a terrible idea to define a function as the exception handler? This way, any dev can replace it with another one should they want to. It may be too early to think about this, I'm just thinking that the behaviour on error may different from one to another. So if I could define an _onException_ function, that may be handy. Actually, a few of those could be defined by default, and could be mixed together à la Redux Middleware. So you could have the defaults "staleOnNetworkError" and "staleOnAnyError", combining the two makes no sense in this case, but perhaps I want to handle all 404s with my custon "respond404OnError". Urgh, I'm probably over thinking this.

4. Would there be another way to re-use the same _uuid_. Reading the code, it looks like there is an undocumented case where _uuid_ could be set in the config, but really we never want them to do that.

5. I would not automatically set one config according to the other, that leads to unexpected results. I think it's fair to document that if you want stale on error, you have to keep stale data when it's expired. Yesterday I was thinking that I might need to be able to override some config as I'm performing the request, such as:

```
axios.get(..., {
  cache: {
    readOnError: true
  }
})
```
That is for another issue, but if that becomes the case, it's easier if the config does not try to be smart and simply observes whichever settings where set. In fact, perhaps debug mode could output the config after it's been merged with the defaults.

Sorry, that was a long post. Thanks for considering my suggestion nonetheless!

I noticed you were from France. It's funny that both of us would be French-speaking but converse in English. Heh!

**Comment by RasCarlito** [comment]
Sorry for not getting back to you on your suggestions (at work right now) which are really good btw!

I'll get back to you asap ;)

Cheers

**Comment by FMCorz** [comment]
Heh, no problem! I'm at UTC+8, and it's late, so I should probably be doing something than checking Github :smile:.

**Comment by RasCarlito** [comment]
Ahaha have a beer and go to sleep ;)

**Comment by RasCarlito** [comment]
@FMCorz I'm getting back on this horse! Don't know if you're still using this lib 😅 

I've not yet decided exactly how to handle things but using functions to catch and handle errors in the user land would be very nice I think.

Anyone else got suggestions for this? Use cases maybe?

Cheers

**Comment by FMCorz** [comment]
Hi @RasCarlito,

Yes, I'm still using your library. This is no longer very fresh in my memory, but here is the adapter I wrote:

https://gist.github.com/FMCorz/b5807bec55a1906ab51ac0c7c0a412d0

You'll notice that I prefer the verbose approach where the cache config defines that it should keep the data even when it's stale. It also includes support for grouping caches, which is quite a hack but it works. Lastly, it's possible to identify whether the cache was retrieved due to a network error.

**Comment by FMCorz** [comment]
Hi @RasCarlito,

Yes, I'm still using your library. This is no longer very fresh in my memory, but here is the adapter I wrote:

https://gist.github.com/FMCorz/b5807bec55a1906ab51ac0c7c0a412d0

You'll notice that I prefer the verbose approach where the cache config defines that it should keep the data even when it's stale. It also includes support for grouping caches, which is quite a hack but it works. Lastly, it's possible to identify whether the cache was retrieved due to a network error.

**Comment by RasCarlito** [comment]
Hi @FMCorz 

Took a lot of your suggestions into account and updated this PR 😄 

It does not handle request groups for cache clearing but I think something could build it on top of #54 

What do you think?

Will get this merged soon.

Cheers 🍻

**Comment by RasCarlito** [comment]
It is a lot simpler than some things you suggested but I think it's a good start 😄

**Pull request merged**
