### PR TITLE
Per req cache bypass

### PR DESCRIPTION
**Pull request by jahead**
possible Implementation for #68 

I have not rebuilt the dist. On my machine, I can't build with the version of webpack-cli/webpack that's defined in this package.json. 

I upgrade the packages and the problem goes away. but that should be referenced in a different pr. 

The related error is here:
https://github.com/webpack/webpack-cli/issues/607

### CODE REVIEW

**Comment by RasCarlito** [comment]
Thanks for this PR!

Very simple implementation, looks good 👍 

What do you think about only accepting the `ignoreCache` parameters as a per request option. Because setting `ignoreCache` globally makes no sense right?
Although to achieve this we need to change `src/config.js` quite a bit. What do you think?

Else we just need to add some documentation in readme and we're good to go!

**Comment by RasCarlito** [comment]
I'll merge this as is and maybe work on it a bit more.

Thanks again for your contribution @jahead 🎉

**Comment by jahead** [comment]
Sorry, work got a little busy here. You are correct, but I wonder if could just put a throw case in the merge code to stop someone shooting themselves in the foot. do you want me to open another issue/PR

**Comment by RasCarlito** [comment]
No worries @jahead ^^

If you've got time I'll gladly accept another PR 😄 
A throw should be enough.

Cheers

**Pull request merged**
