### PR TITLE
chore(typings): Add simple TypeDefinition for RedisStore

### PR DESCRIPTION
**Pull request by Ragyal**
Hotfix for #110

### CODE REVIEW

**Comment by RasCarlito** [comment]
Awesome! Thanks for the fix @Ragyal

**Comment by ovstackelberg** [comment]
@RasCarlito when will this be released?

**Comment by RasCarlito** [comment]
@ovstackelberg I was hoping to include some other fixes in the release but haven't had the time to work on it so I'll release this fix alone today at noon (CET).

**Comment by RasCarlito** [comment]
@ovstackelberg released as [v2.4.1](https://github.com/RasCarlito/axios-cache-adapter/releases/tag/2.4.1)

**Pull request merged**
